Fix scrolling Xaero's World Map with LWJGL 3
GTNewHorizons/Hodgepodge pull request #187
Opened 2023-02-25 21:39 UTC by kumquat-ir

Xaero's World Map tries to clamp scroll wheel values by dividing by 120. This does not work with LWJGL 3 since it reports sane scroll wheel values, unlike LWJGL 2.
This makes it use the raw scroll wheel value instead if lwjgl3ify is detected, which makes scrolling work as expected.
Fixes the "unrelated note" in #172

2023-02-25 22:05 UTC, Alexdoru commented
Put Lwg3fi in the targeted Mod in the mixib instead of checking isModLoaded

2023-03-01 01:10 UTC, Alexdoru requested changes

2023-03-01 23:01 UTC, Alexdoru approved these changes

2023-03-02 14:38 UTC, Dream-Master commented
@Alexdoru was this a approve ? Fix ? Merge or not for stable ?

2023-03-03 12:21 UTC, Alexdoru approved these changes

2023-03-03 12:33 UTC, merged