Compact chat
GTNewHorizons/Hodgepodge pull request #243
Opened 2023-09-16 10:29 UTC by Alexdoru

Compacts identical consecutive chat messages together

Also disabled by default the message "You can only sleep at night" rendering above the hotbar

2023-09-16 14:46 UTC, miozune commented
> Also disabled by default the message "You can only sleep at night" rendering above the hotbar

Any reason? It's the same behavior as newer versions of mc

2023-09-16 14:54 UTC, Alexdoru commented
> Any reason? It's the same behavior as newer versions of mc

I thought that it was added to prevent chat spamming, since with compact chat there is no spam anymore I tough I would disable it

2023-09-16 15:16 UTC, miozune commented
Bed message spam was fixed predate hotbar HUD, https://github.com/GTNewHorizons/Hodgepodge/pull/102. I introduced https://github.com/GTNewHorizons/Hodgepodge/pull/205 because it looks more fancy

2023-09-16 15:49 UTC, Alexdoru commented
> Bed message spam was fixed predate hotbar HUD, #102. I introduced #205 because it looks more fancy

It's just my personal opinion, since this pr adds compact chat, I'd prefer to see the bed message in the chat and not above the hotbar, ngl when testing at first I didn't even see the bed message above the hotbar until I went into the git log to find what happened lol.

Feel free to put the setting back the true by default if you want

2023-09-16 18:46 UTC, glowredman requested changes
I agree with @miozune that the current behaviour should be kept.

2023-09-16 18:46 UTC, glowredman commented on src/main/java/com/mitchej123/hodgepodge/client/chat/ChatHandler.java
> +    public static boolean tryCompactMessage(IChatComponent imsg, @SuppressWarnings("rawtypes") List chatLines) {
Use `List<ChatLine>`

2023-09-16 18:46 UTC, glowredman commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
> +    private List chatLines;
Use `List<ChatLine>`

2023-09-16 18:46 UTC, glowredman commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
> +    private List field_146253_i; // drawnChatLines
Use `List<ChatLine>`

2023-09-16 18:46 UTC, glowredman commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
> +            @SuppressWarnings("rawtypes") ArrayList arraylist) {
Use `ArrayList<IChatComponent>`

2023-09-16 19:08 UTC, Alexdoru commented
I did not add the types at first because I did not know how it would behave with the source code that doesn't have them

2023-09-16 19:14 UTC, Dream-Master commented
@Alexdoru can you resolve the conflict ?

2023-09-17 12:40 UTC, glowredman approved these changes

2023-09-17 12:42 UTC, merged