Fix EffectRenderer keeping reference to world instance when leaving world
GTNewHorizons/Hodgepodge pull request #278
Opened 2023-11-13 23:20 UTC by tth05

2023-11-13 23:45 UTC, Alexdoru requested changes

2023-11-13 23:45 UTC, Alexdoru commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_ClearEffectRenderer.java
> +        if (worldClient == null) {
I see that the vanilla code in this method is using a null check on the effectRenderer field before calling that method, can you do the same thing ?

2023-11-13 23:45 UTC, Alexdoru commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_ClearEffectRenderer.java
> +            at = @At(value = "HEAD"))
can you inject right before it assigns the `this.theWorld = worldClientIn;` and not at the head of the method please

2023-11-13 23:54 UTC, Alexdoru commented
This method says to call it with null to clean, why not do it as well, could that be a leak too

![image](https://github.com/GTNewHorizons/Hodgepodge/assets/57050655/7467830c-68c2-45b3-9979-b9c1a106c979)

2023-11-14 16:15 UTC, tth05 commented
I also added another fix for RenderGlobal

2023-11-14 17:24 UTC, Alexdoru requested changes

2023-11-14 17:24 UTC, Alexdoru commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_ClearRenderersWorldLeak.java
> +                    opcode = Opcodes.PUTFIELD))
can you put `shift = At.Shift.AFTER`

2023-11-14 19:02 UTC, tth05 commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal_FixWordLeak.java
> +            worldRenderers = null;
Sure, although that method does not do anything useful

2023-11-14 19:36 UTC, Alexdoru commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal_FixWordLeak.java
> +            worldRenderers = null;
it sets the world field to null, idk if that's useful, i'm suggesting

2023-11-14 19:53 UTC, Alexdoru commented on src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal_FixWordLeak.java
> +            worldRenderers = null;
if you think it is useless you can remove it

2023-11-15 16:02 UTC, Alexdoru approved these changes

2023-11-15 16:03 UTC, Alexdoru commented
can you rebase your branch on top of master @tth05

2023-11-15 16:35 UTC, merged