Update MixinGuiChat_OpenLinks.java
GTNewHorizons/Hodgepodge pull request #441
Opened 2024-11-18 23:34 UTC by mitchej123

Saw this error floating around in the wild:
`Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method func_146407_a in mixins.hodgepodge.early.json:minecraft.MixinGuiChat_OpenLinks from mod hodgepodge cannot reduce visibiliy of PROTECTED target method`

Apparently someone's AT'd the field and made it protected.... haven't tested this (commiting from Github) so please verify before merging

2024-11-20 01:52 UTC, reallydrained commented
I tested this with the artifact .jar and it fixed the issue =D  (I was the one who reported the error/crash log)

Could only use v2.5.71 or lower before without it crashing but now no crash!

2024-11-20 02:37 UTC, Alexdoru commented
Another reason go not use AT 🤡

2024-11-20 02:38 UTC, Alexdoru requested changes
To solve that issue you should instead of the overwrite inject at head and always cancel

2024-11-20 06:35 UTC, mitchej123 commented
> To solve that issue you should instead of the overwrite inject at head and always cancel

go look at the git blame of who did the original fix :P

2024-11-20 07:05 UTC, Alexdoru commented
I know it's me that did the original fix. It's only now broken because of an external factor which is someone using AT. This example is one more reason mixin accessors and invokers are superior.

Also blaming me for the original code doesn't make my review less valid. In your current fix you make it protect but now it will crash too if another AT makes it public. So your fix doesn't actually fix the underlying problem.

2024-11-20 07:41 UTC, mitchej123 commented
It solves the crash.  I'm on vacation and I'm not going to do a more involved fix.  I'm also fine just making it public, I don't need to do too much work to work around this crash.

2024-11-20 07:58 UTC, Glease commented
So @Alexdoru can you maybe open a new PR to implement what you mentioned? since mitch is obviously too occupied to follow up on this.

If neither of you have time, I might be able to do something later

2024-11-20 08:09 UTC, Alexdoru commented
I did it

2024-11-20 10:53 UTC, Alexdoru approved these changes

2024-11-20 11:39 UTC, merged

2024-11-21 02:44 UTC, reallydrained commented
The new version ([Build and test #1158](https://github.com/GTNewHorizons/Hodgepodge/actions/runs/11929219861)) also works, no crash!