Configurable ender quarry RF storage
GTNewHorizons/Hodgepodge pull request #446
Opened 2024-12-08 04:35 UTC by Midnight145

This removes the need for GTNH's modified version of EU2, where the only changes between the modified version and release are a mitigation for one of the dupes fixed in #438, and to modify the Ender Quarry's storage (set to 200,000,000 instead of 10,000,000).

Currently, it adds one new config option, and you can set the option to 0 to disable it. It defaults to the original value of 10,000,000 instead of the modified version currently in GTNH.

This also cleans up my ContainerFilingCabinet mixin that patches the dupe mentioned above to extend Container and shadow methods when necessary, instead of doing `(ContainerFilingCabinet) (Object) this`

2024-12-08 04:37 UTC, Midnight145 commented
i hate spotless so much

2024-12-09 19:04 UTC, Midnight145 commented
(Briefly talked about this on Discord) 
Unsure if this is best placed in hodgepodge or somewhere else,  as this is more of a balance change than a bugfix, feel free to redirect me to somewhere else if it should go there instead.

2024-12-10 09:12 UTC, wlhlm requested changes

2024-12-10 09:12 UTC, wlhlm commented on src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
> +    @Config.Comment("Ender Quarry RF Storage Override (0 to disable)")
Maybe mention the original value? Like
```suggestion
    @Config.Comment("Ender Quarry RF Storage Override (ExU default value: 10000000) (0 to use default value)")
```

2024-12-10 09:12 UTC, wlhlm commented on src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinContainerFilingCabinet.java
Changes look good, but please put this in a separate PR.

2024-12-10 09:45 UTC, wlhlm approved these changes

2024-12-10 09:49 UTC, merged